# Module 2 Classification

In [6]:
from sklearn import datasets

In [3]:
import pandas as pd

## Step 1: Load Data

In [4]:
# Load Iris dataset
iris = datasets.load_iris()

In [14]:
# iris

In [11]:
X,y = iris.data,iris.target
# X = iris.data
# y = iris.target

In [15]:
X.shape

(150, 4)

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Step 2 Split and Randomize Data

In [18]:
# Split and Randomize the data
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y,
                                                 test_size=0.25,
                                                 random_state=33)

In [19]:
len(y_train), len(y_test)

(112, 38)

In [20]:
X_train.shape, X_test.shape

((112, 4), (38, 4))

## Step 3 Define the Classifier/Model

In [21]:
# KNN Classifier

# from sklearn import neighbors
# clf = neighbors.KNeighborsClassifier()

# More optimized because only get what you need from the package
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()

## Step 4 Train the Model

In [23]:
clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

## Step 5 Evaluate the Model

In [25]:
clf.score(X_test,y_test)

0.9473684210526315

In [26]:
y_test_pred = clf.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_pred)

0.9473684210526315

## Step 6: Save the Model

In [25]:
from sklearn.externals import joblib
joblib.dump(clf, 'mymodel.pkl') 

['mymodel.pkl']

## Step 7: Load the Model & Prediction

In [26]:
clf = joblib.load('mymodel.pkl')
clf

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [27]:
clf.predict(X_test)

array([1, 1, 0, 1, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 1, 1, 0, 1, 2, 0, 0,
       2, 0, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1])

In [33]:
clf.predict([[6.7,3.1,4.7,1.5],
             [6.7,3.1,4.7,1.5]])

array([1, 1])

In [34]:
clf.predict([[6.7,3.1,4.7,1.5]])

array([1])

## Ex: Classifiers

In [45]:
import pandas as pd
credit = pd.read_csv('data/credit.csv')

In [46]:
# credit.head(10)

In [47]:
# credit.describe()

In [48]:
# credit['Creditability'] #series

In [49]:
credit['Creditability'].unique()

array([1, 0])

In [50]:
credit['Creditability'].value_counts()

1    700
0    300
Name: Creditability, dtype: int64

In [51]:
y = credit['Creditability']
X = credit.drop(columns = ['Creditability'])

In [52]:
X_train,X_test,y_train,y_test = train_test_split(X, y,
                                                 test_size=0.25,
                                                 random_state=33)

In [81]:
# KNN Classifier

from sklearn import neighbors 
# clf = neighbors.KNeighborsClassifier()
clf = neighbors.KNeighborsClassifier(n_neighbors = 50)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.68

In [70]:
# SVM Classifier
# from sklearn import svm 
# clf = svm.SVC()

from sklearn.svm import SVC
clf = SVC(random_state=33)
# WARNING: Very slow
# clf = svm.SVC(kernel = 'rbf')
# clf = svm.SVC(kernel = 'linear')
# clf = svm.SVC(kernel = 'poly')
# clf = svm.SVC(kernel = 'sigmoid')
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.672

In [71]:
# Guassian Navie Bayes Classifer

from sklearn import naive_bayes
clf = naive_bayes.GaussianNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.724

In [84]:
# SGD Classifer

from sklearn import linear_model
clf = linear_model.SGDClassifier(random_state = 33)
clf = linear_model.SGDClassifier(penalty = 'l2')
# clf = linear_model.SGDClassifier(penalty = 'l1')
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.672

In [73]:
# import numpy as np
# np.random.seed(33)

In [96]:
# Decision Tree Classifer

from sklearn import tree
clf = tree.DecisionTreeClassifier(random_state = 33)
# clf = tree.DecisionTreeClassifier(random_state = 33, 
#                                   min_samples_split = 100)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
# clf.score(X_train,y_train)

0.704

In [94]:
# clf.predict_proba(X_test)

In [112]:
from sklearn.model_selection import GridSearchCV
parameters = {'min_samples_split':[8, 10], 
              'max_depth': range(6, 11, 2)}
gridsearcher = GridSearchCV(estimator = tree.DecisionTreeClassifier(random_state = 33), 
                            param_grid = parameters, cv=5)
gridsearcher.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=33,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'min_samples_split': [8, 10], 'max_depth': range(6, 11, 2)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [106]:
gridsearcher.best_params_

{'max_depth': 6, 'min_samples_split': 8}

In [107]:
tree_clf = gridsearcher.best_estimator_

In [110]:
tree_clf.predict(X_test)

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0])

In [49]:
gridsearcher.score(X_test,y_test)

0.66

In [50]:
!pip install graphviz

In [51]:
from sklearn import tree
# clf = tree.DecisionTreeClassifier()
tree_clf = tree.DecisionTreeClassifier(min_samples_split = 100)
tree_clf.fit(X_train,y_train)
tree_clf.score(X_test,y_test)

0.75

In [52]:
import graphviz
from sklearn import tree
dot_data = tree.export_graphviz(tree_clf, out_file=None,
                                feature_names = X_train.columns,
                                filled = False, rounded = True)
graph = graphviz.Source(dot_data, format="png")
graph.render('tree')

'tree.png'

## Ensemble Method

In [116]:
# Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators = 10, random_state = 33)
clf.fit(X_train,y_train)
print(clf.score(X_test,y_test))

clf = RandomForestClassifier(n_estimators = 100, random_state = 33)
clf.fit(X_train,y_train)
print(clf.score(X_test,y_test))

clf = RandomForestClassifier(n_estimators = 1000, random_state = 33)
clf.fit(X_train,y_train)
print(clf.score(X_test,y_test))

clf = RandomForestClassifier(n_estimators = 10000, random_state = 33)
clf.fit(X_train,y_train)
print(clf.score(X_test,y_test))

0.732
0.752
0.764
0.756


In [92]:
clf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=2019, verbose=0,
            warm_start=False)

In [91]:
clf.feature_importances_

array([0.11100245, 0.09930628, 0.05347698, 0.0614115 , 0.13631374,
       0.04928339, 0.04922782, 0.04261773, 0.03658993, 0.01897287,
       0.03798085, 0.05109467, 0.11055488, 0.02489272, 0.02507968,
       0.02198642, 0.02915012, 0.01349232, 0.02242882, 0.00513683])

In [101]:
importances = pd.DataFrame(data = {'column_name': X_train.columns,
                    'feature_importance': clf.feature_importances_})
importances.sort_values(['feature_importance'], ascending = False)
# importances['feature_importance'].sum()

column_name  feature_importance
4                       Credit Amount            0.131735
12                        Age (years)            0.108584
1          Duration of Credit (month)            0.098389
0                     Account Balance            0.093161
2   Payment Status of Previous Credit            0.063956
3                             Purpose            0.061897
6        Length of current employment            0.059131
5                Value Savings/Stocks            0.050914
11      Most valuable available asset            0.044912
7                 Instalment per cent            0.043924
10        Duration in Current address            0.040362
8                Sex & Marital Status            0.035298
16                         Occupation            0.032898
14                  Type of apartment            0.028185
13                 Concurrent Credits            0.026320
15         No of Credits at this Bank            0.024727
18                          Telephone            0.020407
17                   No of dependents            0.016337
9                          Guarantors            0.015609
19                     Foreign Worker            0.003251

In [97]:
importances['feature_importance'].sum()

0.9999999999999999

In [118]:
# Gradient Boosting Tree Classifier

from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(random_state = 33)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.764

## Ex: Save the Model

In [28]:
from sklearn.externals import joblib
joblib.dump(clf, 'credit.pkl') 

['credit.pkl']

## Ex: Load the Model

In [29]:
from sklearn.externals import joblib
clf2 = joblib.load('credit.pkl')

In [30]:
import numpy as np
y_pred = clf2.predict(X_test)

## Ex: Customer Transaction Prediction

In [154]:
transaction = pd.read_csv('data/customer_transaction.csv')

In [155]:
transaction.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4    var_5  \
0   train_73297       0   7.4516 -1.0710   7.6644  6.6644  10.6747 -13.2679   
1   train_79756       1  14.6469  0.2512   8.5101  6.6862  12.0408   4.6785   
2  train_138043       0  11.9599 -5.8784   7.9067  6.5769   7.4192  -5.8442   
3   train_33678       0   9.0334  0.4932  11.5369  5.6356  10.8020 -11.6920   
4  train_133321       0   8.6398 -0.4785  16.9614  2.6484   9.9465  -3.0443   

    var_6    var_7  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  5.9301  21.5816  ...   7.0792   6.0545   2.4383   0.3335  15.5773   0.4564   
1  6.9680  19.3274  ...   4.0484   6.4801   3.5978   3.1407  23.9872   1.5292   
2  4.8585  14.3521  ...  -5.3537   7.5983   3.9085   6.3675  21.7338  -0.5874   
3  4.8708  13.2391  ...   5.1401   9.1957   2.4340   5.5633  16.7777   1.9633   
4  6.1818  12.0435  ...   1.6368   4.9795   0.3358   1.0997  21.3309   0.7617   

   var_196  var_197  var_198  var_199  
0   1.6129   7.8048  15.8583  -3.7730  
1  -6.4050   8.1170  12.6881  -7.7544  
2  -6.0970   8.5625  20.0341   3.3469  
3  -3.2447   8.7895  14.6535   2.2478  
4   3.2567   8.1391   8.5642 -14.1064  

[5 rows x 202 columns]

In [156]:
transaction['target'].value_counts()

0    1796
1     204
Name: target, dtype: int64

In [157]:
transaction.shape

(2000, 202)

In [158]:
y = transaction['target']
X = transaction.drop(columns = ['ID_code', 'target'])

In [159]:
# from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                 test_size=0.25,
                                                 random_state=33)

In [160]:
# KNN Classifier

from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.894

In [161]:
# # SVM Classifier

from sklearn import svm 
clf = svm.SVC(random_state = 33)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9

In [162]:
# # Guassian Navie Bayes Classifer

from sklearn import naive_bayes
clf = naive_bayes.GaussianNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9

In [163]:
# SGD Classifer

from sklearn import linear_model
clf = linear_model.SGDClassifier(random_state = 33)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.754

In [164]:
# Decision Tree Classifer

from sklearn import tree
clf = tree.DecisionTreeClassifier(random_state = 33)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.79

In [165]:
# Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 33)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.902

In [166]:
# Gradient Boosting Tree Classifier

from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(random_state = 33)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.898

## Confusion Matrix

In [110]:
from sklearn.metrics import confusion_matrix
y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
confusion_matrix(y_true, y_pred, labels=["ant", "bird", "cat"])


array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]])

## Ex: Confusion Matrix

In [169]:
# SVM Classifier

from sklearn import svm 
svm_clf = svm.SVC(random_state = 33)
svm_clf.fit(X_train,y_train)
svm_clf.score(X_test,y_test)

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9

In [171]:
y_test.value_counts()

0    450
1     50
Name: target, dtype: int64

In [177]:
from sklearn.metrics import confusion_matrix

y_pred = svm_clf.predict(X_test)
confusion_matrix(y_test, y_pred, labels = [0, 1])

array([[450,   0],
       [ 50,   0]])

In [178]:
# KNN Classifier

from sklearn import neighbors
knn_clf = neighbors.KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
knn_clf.score(X_test,y_test)

0.894

In [179]:
from sklearn.metrics import confusion_matrix

y_pred = knn_clf.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[447,   3],
       [ 50,   0]])

In [180]:
y_test.value_counts()

0    450
1     50
Name: target, dtype: int64

In [181]:
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[448,   2],
       [ 49,   1]])

## Classification Report

In [182]:
from sklearn.metrics import classification_report
y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
print(classification_report(y_true, y_pred, 
                            labels=["ant", "bird", "cat"]))

              precision    recall  f1-score   support

         ant       0.67      1.00      0.80         2
        bird       0.00      0.00      0.00         1
         cat       0.67      0.67      0.67         3

   micro avg       0.67      0.67      0.67         6
   macro avg       0.44      0.56      0.49         6
weighted avg       0.56      0.67      0.60         6



/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Ex: Classification Report

In [183]:
from sklearn.metrics import classification_report
y_pred = svm_clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95       450
           1       0.00      0.00      0.00        50

   micro avg       0.90      0.90      0.90       500
   macro avg       0.45      0.50      0.47       500
weighted avg       0.81      0.90      0.85       500



/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [184]:
from sklearn.metrics import classification_report
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95       450
           1       0.33      0.02      0.04        50

   micro avg       0.90      0.90      0.90       500
   macro avg       0.62      0.51      0.49       500
weighted avg       0.84      0.90      0.86       500



In [107]:
classification_report(y_test,y_pred).split('\n')

['              precision    recall  f1-score   support',
 '',
 '           0       0.65      0.43      0.51        82',
 '           1       0.81      0.91      0.86       218',
 '',
 '   micro avg       0.78      0.78      0.78       300',
 '   macro avg       0.73      0.67      0.69       300',
 'weighted avg       0.76      0.78      0.76       300',
 '']

In [185]:
from sklearn.metrics import classification_report
y_pred = knn_clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.99      0.94       450
           1       0.00      0.00      0.00        50

   micro avg       0.89      0.89      0.89       500
   macro avg       0.45      0.50      0.47       500
weighted avg       0.81      0.89      0.85       500



In [140]:
credit['Credit Amount Binned'] = pd.cut(credit['Credit Amount'], bins = 10, labels = range(0,10))
# credit[['Credit Amount', 'Credit Amount Binned']]

In [141]:
credit.head()

Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18   
1              1                1                           9   
2              1                2                          12   
3              1                1                          12   
4              1                1                          12   

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049   
1                                  4        0           2799   
2                                  2        9            841   
3                                  4        0           2122   
4                                  4        0           2171   

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4   
1                     1                             3                    2   
2                     2                             4                    2   
3                     1                             3                    3   
4                     1                             3                    4   

   Sex & Marital Status  ...  Age (years)  Concurrent Credits  \
0                     2  ...           21                   3   
1                     3  ...           36                   3   
2                     2  ...           23                   3   
3                     3  ...           39                   3   
4                     3  ...           38                   1   

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3   
1                  1                           2           3   
2                  1                           1           2   
3                  1                           2           2   
4                  2                           2           2   

   No of dependents  Telephone  Foreign Worker  Credit Amount binned  \
0                 1          1               1     (231.826, 9337.0]   
1                 2          1               1     (231.826, 9337.0]   
2                 1          1               1     (231.826, 9337.0]   
3                 2          1               2     (231.826, 9337.0]   
4                 1          1               2     (231.826, 9337.0]   

   Credit Amount Binned  
0                     0  
1                     1  
2                     0  
3                     1  
4                     1  

[5 rows x 23 columns]

In [156]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
credit_t = encoder.fit_transform(credit.values)
credit_t

/Users/anqitu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


<1000x1079 sparse matrix of type '<class 'numpy.float64'>'
	with 21000 stored elements in Compressed Sparse Row format>

In [135]:
pd.get_dummies(credit, columns = ['Account Balance'])

Creditability  Duration of Credit (month)  \
0                1                          18   
1                1                           9   
2                1                          12   
3                1                          12   
4                1                          12   
5                1                          10   
6                1                           8   
7                1                           6   
8                1                          18   
9                1                          24   
10               1                          11   
11               1                          30   
12               1                           6   
13               1                          48   
14               1                          18   
15               1                           6   
16               1                          11   
17               1                          18   
18               1                          36   
19               1                          11   
20               1                           6   
21               1                          12   
22               0                          36   
23               1                          12   
24               1                           6   
25               1                          11   
26               1                          12   
27               1                           9   
28               1                          15   
29               1                          42   
..             ...                         ...   
970              0                          48   
971              0                          27   
972              0                          18   
973              0                          45   
974              0                           6   
975              0                          30   
976              0                          48   
977              0                           6   
978              0                          12   
979              0                          12   
980              0                          24   
981              0                          18   
982              0                          48   
983              0                          18   
984              0                          48   
985              0                          12   
986              0                          14   
987              0                          12   
988              0                          18   
989              0                          24   
990              0                          18   
991              0                          24   
992              0                          18   
993              0                          18   
994              0                          12   
995              0                          24   
996              0                          24   
997              0                          21   
998              0                          12   
999              0                          30   

     Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                    4        2           1049   
1                                    4        0           2799   
2                                    2        9            841   
3                                    4        0           2122   
4                                    4        0           2171   
5                                    4        0           2241   
6                                    4        0           3398   
7                                    4        0           1361   
8                                    4        3           1098   
9                                    2        3           3758   
10                                   4        0           3905   
11                                   4        1           6187   
12                                   4        

In [115]:
credit['Credit Amount'].describe()

count     1000.00000
mean      3271.24800
std       2822.75176
min        250.00000
25%       1365.50000
50%       2319.50000
75%       3972.25000
max      18424.00000
Name: Credit Amount, dtype: float64

In [129]:
credit.nunique()

Creditability                          2
Account Balance                        4
Duration of Credit (month)            33
Payment Status of Previous Credit      5
Purpose                               10
Credit Amount                        923
Value Savings/Stocks                   5
Length of current employment           5
Instalment per cent                    4
Sex & Marital Status                   4
Guarantors                             3
Duration in Current address            4
Most valuable available asset          4
Age (years)                           53
Concurrent Credits                     3
Type of apartment                      3
No of Credits at this Bank             4
Occupation                             4
No of dependents                       2
Telephone                              2
Foreign Worker                         2
Credit Amount binned                   2
Credit Amount Binned                  10
dtype: int64

## Markdown